[package]
name = "rusty_scheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rusty_scheme"
path = "src/lib/mod.rs"

[dependencies]
nom = "7"